let CATALOG = [
  {
    name: "JavaScript",
    img: "./Public/Images/js.png",
    price: "400",
    filter: "lang",
    text: "Lorem lorem lorem Lorem lorem lorem Lorem lorem lorem",
    low: "Jun",
    hard: "Midl",
  },
  {
    name: "C++",
    img: "./Public/Images/c-.png",
    price: "400",
    text: "Lorem lorem lorem Lorem lorem lorem Lorem lorem lorem",
    low: "Jun",
    hard: "Midl",
    filter: "lang",
  },
  {
    name: "Python",
    img: "./Public/Images/python.png",
    price: "400",
    text: "Lorem lorem lorem Lorem lorem lorem Lorem lorem lorem",
    low: "Jun",
    hard: "Midl",
    filter: "lang",
  },
  {
    name: "Photoshop",
    img: "./Public/Images/adobe-photoshop.png",
    price: "450",
    filter: "new",
    text: "Lorem lorem lorem Lorem lorem lorem Lorem lorem lorem",
    low: "Jun",
    hard: "Midl",
  },
  {
    name: "Microsoft Office",
    img: "./Public/Images/word.png",
    price: "400",
    filter: "rich",
    text: "Lorem lorem lorem Lorem lorem lorem Lorem lorem lorem",
    low: "Jun",
    hard: "Midl",
  },
];
